//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using SmartBiz.MDMAPI.Common.Entities;
        
    
    public partial class MDMEntities : DbContext
    {
        public MDMEntities()
            : base("name=MDMEntities")
        {  
    	 this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ERP_AgentBrokerSalesMan> ERP_AgentBrokerSalesMan { get; set; }
        public DbSet<ERP_Document> ERP_Document { get; set; }
        public DbSet<ERP_DocumentAttributes> ERP_DocumentAttributes { get; set; }
        public DbSet<ERP_DocumentAttributesBankInfo> ERP_DocumentAttributesBankInfo { get; set; }
        public DbSet<ERP_DocumentAttributesRef> ERP_DocumentAttributesRef { get; set; }
        public DbSet<ERP_LastTransactionInfo> ERP_LastTransactionInfo { get; set; }
        public DbSet<ERP_Period> ERP_Period { get; set; }
        public DbSet<ERP_ProcessControl> ERP_ProcessControl { get; set; }
        public DbSet<ERP_SubModule> ERP_SubModule { get; set; }
        public DbSet<ERP_UnitConversion> ERP_UnitConversion { get; set; }
        public DbSet<ERP_UnitDefinition> ERP_UnitDefinition { get; set; }
        public DbSet<FIN_AccountSubType> FIN_AccountSubType { get; set; }
        public DbSet<FIN_AccountSubTypeCategory> FIN_AccountSubTypeCategory { get; set; }
        public DbSet<FIN_AccountType> FIN_AccountType { get; set; }
        public DbSet<FIN_Area> FIN_Area { get; set; }
        public DbSet<FIN_Bank> FIN_Bank { get; set; }
        public DbSet<FIN_BankAccount> FIN_BankAccount { get; set; }
        public DbSet<FIN_BankBranch> FIN_BankBranch { get; set; }
        public DbSet<FIN_CostCenter> FIN_CostCenter { get; set; }
        public DbSet<FIN_CostCenterwiseConfiguration> FIN_CostCenterwiseConfiguration { get; set; }
        public DbSet<FIN_Currency> FIN_Currency { get; set; }
        public DbSet<FIN_CurrencyExchangeRate> FIN_CurrencyExchangeRate { get; set; }
        public DbSet<FIN_CustomerSupplier_Info> FIN_CustomerSupplier_Info { get; set; }
        public DbSet<FIN_CustomerSupplierBank> FIN_CustomerSupplierBank { get; set; }
        public DbSet<FIN_CustSupPeriodBalance> FIN_CustSupPeriodBalance { get; set; }
        public DbSet<FIN_GeneralLedgerAccount> FIN_GeneralLedgerAccount { get; set; }
        public DbSet<FIN_GeneralLedgerSummary> FIN_GeneralLedgerSummary { get; set; }
        public DbSet<FIN_PrimaryTransaction> FIN_PrimaryTransaction { get; set; }
        public DbSet<FIN_ProfitLostType> FIN_ProfitLostType { get; set; }
        public DbSet<FIN_Region> FIN_Region { get; set; }
        public DbSet<FIN_SecondaryTransaction> FIN_SecondaryTransaction { get; set; }
        public DbSet<FIN_SpecialAccountType> FIN_SpecialAccountType { get; set; }
        public DbSet<FIN_TxnReference> FIN_TxnReference { get; set; }
        public DbSet<HR_EMP_ATTACHMENT> HR_EMP_ATTACHMENT { get; set; }
        public DbSet<HR_EMP_PASSPORT> HR_EMP_PASSPORT { get; set; }
        public DbSet<HR_EMP_RELATIONINFO> HR_EMP_RELATIONINFO { get; set; }
        public DbSet<HR_EMPLOYEE> HR_EMPLOYEE { get; set; }
        public DbSet<ERP_FixedTxnAttributes> ERP_FixedTxnAttributes { get; set; }
        public DbSet<FIN_ControledTransaction> FIN_ControledTransaction { get; set; }
        public DbSet<HR_EMP_EMERGENCY> HR_EMP_EMERGENCY { get; set; }
        public DbSet<HR_EMP_TRAININGS> HR_EMP_TRAININGS { get; set; }
        public DbSet<HR_EMP_TRANSPORT> HR_EMP_TRANSPORT { get; set; }
        public DbSet<HR_EMP_WARNINGS> HR_EMP_WARNINGS { get; set; }
        public DbSet<HR_EMP_MEMBER_DETAIL> HR_EMP_MEMBER_DETAIL { get; set; }
        public DbSet<HR_EMP_QUALIFICATION> HR_EMP_QUALIFICATION { get; set; }
        public DbSet<HR_EMP_WORK_EXPERIENCE> HR_EMP_WORK_EXPERIENCE { get; set; }
        public DbSet<HR_MEMBERSHIP> HR_MEMBERSHIP { get; set; }
        public DbSet<HR_MEMBERSHIP_TYPE> HR_MEMBERSHIP_TYPE { get; set; }
        public DbSet<HR_CORPORATE_TITLE> HR_CORPORATE_TITLE { get; set; }
        public DbSet<HR_COUNTRY> HR_COUNTRY { get; set; }
        public DbSet<HR_CURRENCY> HR_CURRENCY { get; set; }
        public DbSet<HR_DESIGNATION> HR_DESIGNATION { get; set; }
        public DbSet<HR_DISTRICT> HR_DISTRICT { get; set; }
        public DbSet<HR_ELECTORATE> HR_ELECTORATE { get; set; }
        public DbSet<HR_EMPLOYEE_CDWD> HR_EMPLOYEE_CDWD { get; set; }
        public DbSet<HR_EMPLOYEE_EIM_WS> HR_EMPLOYEE_EIM_WS { get; set; }
        public DbSet<HR_EMPLOYEE_JI> HR_EMPLOYEE_JI { get; set; }
        public DbSet<HR_EMPLOYEE_JS> HR_EMPLOYEE_JS { get; set; }
        public DbSet<HR_EMPLOYEE_OC> HR_EMPLOYEE_OC { get; set; }
        public DbSet<HR_EMPLOYEE_PC> HR_EMPLOYEE_PC { get; set; }
        public DbSet<HR_EMPLOYEE_PD> HR_EMPLOYEE_PD { get; set; }
        public DbSet<HR_EMPLOYEE_TD> HR_EMPLOYEE_TD { get; set; }
        public DbSet<HR_JD_CATEGORY> HR_JD_CATEGORY { get; set; }
        public DbSet<HR_LOCATION> HR_LOCATION { get; set; }
        public DbSet<HR_NATIONALITY> HR_NATIONALITY { get; set; }
        public DbSet<HR_PROVINCE> HR_PROVINCE { get; set; }
        public DbSet<HR_RELIGION> HR_RELIGION { get; set; }
        public DbSet<HR_SALARY_GRADE> HR_SALARY_GRADE { get; set; }
        public DbSet<HR_EMP_CASH_BENEFIT> HR_EMP_CASH_BENEFIT { get; set; }
        public DbSet<HR_EMP_NONCASH_BENEFIT> HR_EMP_NONCASH_BENEFIT { get; set; }
        public DbSet<HR_NONCASH_BENEFIT> HR_NONCASH_BENEFIT { get; set; }
        public DbSet<HR_CASH_BENEFIT> HR_CASH_BENEFIT { get; set; }
        public DbSet<HR_EMP_BASICSALARY> HR_EMP_BASICSALARY { get; set; }
        public DbSet<HR_EMP_EXTRA_ACTIVITY> HR_EMP_EXTRA_ACTIVITY { get; set; }
        public DbSet<HR_EMP_JOBSPEC> HR_EMP_JOBSPEC { get; set; }
        public DbSet<HR_EMP_LANGUAGE> HR_EMP_LANGUAGE { get; set; }
        public DbSet<HR_EMP_REPORTTO> HR_EMP_REPORTTO { get; set; }
        public DbSet<HR_LANGUAGE> HR_LANGUAGE { get; set; }
        public DbSet<HR_BANK> HR_BANK { get; set; }
        public DbSet<HR_BRANCH> HR_BRANCH { get; set; }
        public DbSet<HR_EMP_BANK> HR_EMP_BANK { get; set; }
    }
}
