//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class ERP_DocumentAttributes
    {
    	
        public ERP_DocumentAttributes()
        {
            this.ERP_DocumentAttributesRef = new HashSet<ERP_DocumentAttributesRef>();
            this.ERP_LastTransactionInfo = new HashSet<ERP_LastTransactionInfo>();
            this.FIN_CostCenterwiseConfiguration = new HashSet<FIN_CostCenterwiseConfiguration>();
            this.FIN_CostCenterwiseConfiguration1 = new HashSet<FIN_CostCenterwiseConfiguration>();
            this.FIN_CostCenterwiseConfiguration2 = new HashSet<FIN_CostCenterwiseConfiguration>();
            this.FIN_TxnReference = new HashSet<FIN_TxnReference>();
            this.FIN_ControledTransaction = new HashSet<FIN_ControledTransaction>();
            this.ERP_FixedTxnAttributes = new HashSet<ERP_FixedTxnAttributes>();
        }
    
    	[DataMember]
    	public string DocCode { get; set; }
    	[DataMember]
    	public string TxCode { get; set; }
    	[DataMember]
    	public string ShortName { get; set; }
    	[DataMember]
    	public string LongName { get; set; }
    	[DataMember]
    	public Nullable<int> DB_ToGL_Flag { get; set; }
    	[DataMember]
    	public Nullable<int> CR_ToGL_Flag { get; set; }
    	[DataMember]
    	public Nullable<int> FixedToCustSup_Flag { get; set; }
    	[DataMember]
    	public string FixedCustSupCode { get; set; }
    	[DataMember]
    	public Nullable<int> ChequePrint_Flag { get; set; }
    	[DataMember]
    	public Nullable<int> AmountTally_Flag { get; set; }
    	[DataMember]
    	public Nullable<int> FixedBankAcc_Flag { get; set; }
    	[DataMember]
    	public Nullable<int> AuthorizeRequired_Flag { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual ERP_Document ERP_Document { get; set; }
    	[DataMember]
        public virtual ERP_DocumentAttributesBankInfo ERP_DocumentAttributesBankInfo { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_DocumentAttributesRef> ERP_DocumentAttributesRef { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_LastTransactionInfo> ERP_LastTransactionInfo { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_CostCenterwiseConfiguration> FIN_CostCenterwiseConfiguration { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_CostCenterwiseConfiguration> FIN_CostCenterwiseConfiguration1 { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_CostCenterwiseConfiguration> FIN_CostCenterwiseConfiguration2 { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_TxnReference> FIN_TxnReference { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_ControledTransaction> FIN_ControledTransaction { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_FixedTxnAttributes> ERP_FixedTxnAttributes { get; set; }
    public ERP_DocumentAttributes Clone(){
    	return this.MemberwiseClone() as ERP_DocumentAttributes;
    }
    public override String ToString(){
       return DocCode+"-"+TxCode;
    }
    }
}
