//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class ERP_Document
    {
    	
        public ERP_Document()
        {
            this.ERP_DocumentAttributes = new HashSet<ERP_DocumentAttributes>();
            this.FIN_BankAccount = new HashSet<FIN_BankAccount>();
        }
    
    	[DataMember]
    	public string DocCode { get; set; }
    	[DataMember]
    	public string ProductCode { get; set; }
    	[DataMember]
    	public string SubSystemCode { get; set; }
    	[DataMember]
    	public int DocType { get; set; }
    	[DataMember]
    	public string DocName { get; set; }
    	[DataMember]
    	public int DocumentMode { get; set; }
    	[DataMember]
    	public Nullable<int> ChequeSeqFlag { get; set; }
    	[DataMember]
    	public Nullable<int> TransferFlag { get; set; }
    	[DataMember]
    	public int TransactionMode { get; set; }
    	[DataMember]
    	public Nullable<int> CashBankFlag { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual ICollection<ERP_DocumentAttributes> ERP_DocumentAttributes { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_BankAccount> FIN_BankAccount { get; set; }
    public ERP_Document Clone(){
    	return this.MemberwiseClone() as ERP_Document;
    }
    public override String ToString(){
       return DocCode.ToString();
    }
    }
}
