//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class ERP_DocumentAttributesRef
    {
    	[DataMember]
    	public string DocCode { get; set; }
    	[DataMember]
    	public string TxCode { get; set; }
    	[DataMember]
    	public short RefNo { get; set; }
    	[DataMember]
    	public Nullable<int> RefValidationCriteria { get; set; }
    	[DataMember]
    	public Nullable<int> RefValidationMethod { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual ERP_DocumentAttributes ERP_DocumentAttributes { get; set; }
    public ERP_DocumentAttributesRef Clone(){
    	return this.MemberwiseClone() as ERP_DocumentAttributesRef;
    }
    public override String ToString(){
       return DocCode.ToString();
    }
    }
}
