//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class FIN_CustomerSupplierBank
    {
    	[DataMember]
    	public Nullable<int> CustSupFlag { get; set; }
    	[DataMember]
    	public string CusSupCode { get; set; }
    	[DataMember]
    	public string BankCode { get; set; }
    	[DataMember]
    	public string BranchCode { get; set; }
    	[DataMember]
    	public string AccountNo { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual FIN_BankBranch FIN_BankBranch { get; set; }
    	[DataMember]
        public virtual FIN_CustomerSupplier_Info FIN_CustomerSupplier_Info { get; set; }
    public FIN_CustomerSupplierBank Clone(){
    	return this.MemberwiseClone() as FIN_CustomerSupplierBank;
    }
    public override String ToString(){
       return CustSupFlag.ToString();
    }
    }
}
