//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class FIN_GeneralLedgerSummary
    {
    	[DataMember]
    	public string AccountNo { get; set; }
    	[DataMember]
    	public string CurrencyCode { get; set; }
    	[DataMember]
    	public int FinancialYear { get; set; }
    	[DataMember]
    	public short AccountingPeriod { get; set; }
    	[DataMember]
    	public Nullable<decimal> OpeningBalanceFCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> OpeningBalanceLCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> DebitMovementFCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> DebitMovementLCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> CreditMovementFCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> CreditMovementLCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> DebitAdjustmentFCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> DebitAdjustmentLCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> CreditAdjustementFCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> CreditAdjustementLCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> ClosingBalanceFCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> ClosingBalanceLCY { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    public FIN_GeneralLedgerSummary Clone(){
    	return this.MemberwiseClone() as FIN_GeneralLedgerSummary;
    }
    public override String ToString(){
       return AccountNo.ToString();
    }
    }
}
