//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class FIN_SecondaryTransaction
    {
    	[DataMember]
    	public string DocCode { get; set; }
    	[DataMember]
    	public string TxCode { get; set; }
    	[DataMember]
    	public int TxSerial { get; set; }
    	[DataMember]
    	public int VoucherNumber { get; set; }
    	[DataMember]
    	public int FinancialYear { get; set; }
    	[DataMember]
    	public int TxnSeqNo { get; set; }
    	[DataMember]
    	public Nullable<int> TransactionStatus { get; set; }
    	[DataMember]
    	public string GLAccountNo { get; set; }
    	[DataMember]
    	public string CostCenterCode { get; set; }
    	[DataMember]
    	public string CurrencyCode { get; set; }
    	[DataMember]
    	public Nullable<decimal> ExRate { get; set; }
    	[DataMember]
    	public string Reference4 { get; set; }
    	[DataMember]
    	public string Reference5 { get; set; }
    	[DataMember]
    	public string Reference6 { get; set; }
    	[DataMember]
    	public Nullable<int> CreditDebit_Flag { get; set; }
    	[DataMember]
    	public Nullable<decimal> AmountLCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> AmountFCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> BalanceAmountLCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> BalanceAmountFCY { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    public FIN_SecondaryTransaction Clone(){
    	return this.MemberwiseClone() as FIN_SecondaryTransaction;
    }
    public override String ToString(){
       return DocCode.ToString();
    }
    }
}
