//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class FIN_CurrencyExchangeRate
    {
    	[DataMember]
    	public string CurrencyCode { get; set; }
    	[DataMember]
    	public short CalenderYear { get; set; }
    	[DataMember]
    	public byte CalenderMonth { get; set; }
    	[DataMember]
    	public Nullable<decimal> StandardRate { get; set; }
    	[DataMember]
    	public Nullable<decimal> BuyRate { get; set; }
    	[DataMember]
    	public Nullable<decimal> MiddleRate { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual FIN_Currency FIN_Currency { get; set; }
    public FIN_CurrencyExchangeRate Clone(){
    	return this.MemberwiseClone() as FIN_CurrencyExchangeRate;
    }
    public override String ToString(){
       return CurrencyCode.ToString();
    }
    }
}
