//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class FIN_BankBranch
    {
    	
        public FIN_BankBranch()
        {
            this.FIN_BankAccount = new HashSet<FIN_BankAccount>();
            this.FIN_CustomerSupplierBank = new HashSet<FIN_CustomerSupplierBank>();
        }
    
    	[DataMember]
    	public string BankCode { get; set; }
    	[DataMember]
    	public string BankBranchCode { get; set; }
    	[DataMember]
    	public string BranchName { get; set; }
    	[DataMember]
    	public string Address1 { get; set; }
    	[DataMember]
    	public string Address2 { get; set; }
    	[DataMember]
    	public string City { get; set; }
    	[DataMember]
    	public string AreaCode { get; set; }
    	[DataMember]
    	public string RegionCode { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual FIN_Area FIN_Area { get; set; }
    	[DataMember]
        public virtual FIN_Bank FIN_Bank { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_BankAccount> FIN_BankAccount { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_CustomerSupplierBank> FIN_CustomerSupplierBank { get; set; }
    public FIN_BankBranch Clone(){
    	return this.MemberwiseClone() as FIN_BankBranch;
    }
    public override String ToString(){
       return BankCode.ToString();
    }
    }
}
