//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class FIN_PrimaryTransaction
    {
    	[DataMember]
    	public string DocCode { get; set; }
    	[DataMember]
    	public string TxCode { get; set; }
    	[DataMember]
    	public int TxSerial { get; set; }
    	[DataMember]
    	public int VoucherNumber { get; set; }
    	[DataMember]
    	public int FinancialYear { get; set; }
    	[DataMember]
    	public Nullable<int> TransactionStatus { get; set; }
    	[DataMember]
    	public Nullable<int> AccountingPeriod { get; set; }
    	[DataMember]
    	public Nullable<int> ProcessPeriod { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EnteredProcessDate { get; set; }
    	[DataMember]
    	public Nullable<int> TransactionType { get; set; }
    	[DataMember]
    	public string SubModuleCode { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> VoucherDate { get; set; }
    	[DataMember]
    	public string Reference1 { get; set; }
    	[DataMember]
    	public string Reference2 { get; set; }
    	[DataMember]
    	public string Reference3 { get; set; }
    	[DataMember]
    	public Nullable<int> CashBank_Flag { get; set; }
    	[DataMember]
    	public Nullable<int> BankTxn_Flag { get; set; }
    	[DataMember]
    	public Nullable<int> ARAPTxn_Flag { get; set; }
    	[DataMember]
    	public Nullable<int> CusSupTxn_Flag { get; set; }
    	[DataMember]
    	public Nullable<int> DueDate { get; set; }
    	[DataMember]
    	public Nullable<decimal> TotalDebitAmt_LCY { get; set; }
    	[DataMember]
    	public Nullable<decimal> TotalCreditAmt_LCY { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    public FIN_PrimaryTransaction Clone(){
    	return this.MemberwiseClone() as FIN_PrimaryTransaction;
    }
    public override String ToString(){
       return DocCode.ToString();
    }
    }
}
