//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class FIN_GeneralLedgerAccount
    {
    	
        public FIN_GeneralLedgerAccount()
        {
            this.ERP_AgentBrokerSalesMan = new HashSet<ERP_AgentBrokerSalesMan>();
            this.FIN_BankAccount = new HashSet<FIN_BankAccount>();
            this.FIN_CostCenterwiseConfiguration = new HashSet<FIN_CostCenterwiseConfiguration>();
            this.FIN_CostCenterwiseConfiguration1 = new HashSet<FIN_CostCenterwiseConfiguration>();
            this.FIN_CostCenterwiseConfiguration2 = new HashSet<FIN_CostCenterwiseConfiguration>();
            this.FIN_CostCenterwiseConfiguration3 = new HashSet<FIN_CostCenterwiseConfiguration>();
            this.FIN_CostCenterwiseConfiguration4 = new HashSet<FIN_CostCenterwiseConfiguration>();
            this.ERP_FixedTxnAttributes = new HashSet<ERP_FixedTxnAttributes>();
            this.ERP_FixedTxnAttributes1 = new HashSet<ERP_FixedTxnAttributes>();
            this.ERP_FixedTxnAttributes2 = new HashSet<ERP_FixedTxnAttributes>();
            this.ERP_FixedTxnAttributes3 = new HashSet<ERP_FixedTxnAttributes>();
            this.ERP_FixedTxnAttributes4 = new HashSet<ERP_FixedTxnAttributes>();
            this.FIN_ControledTransaction = new HashSet<FIN_ControledTransaction>();
        }
    
    	[DataMember]
    	public string AccountNo { get; set; }
    	[DataMember]
    	public Nullable<int> AccountType { get; set; }
    	[DataMember]
    	public Nullable<int> AccountSubtype { get; set; }
    	[DataMember]
    	public Nullable<int> AccountSubtypeCat { get; set; }
    	[DataMember]
    	public string ShortName { get; set; }
    	[DataMember]
    	public string AccountName { get; set; }
    	[DataMember]
    	public Nullable<int> PostableFlag { get; set; }
    	[DataMember]
    	public Nullable<int> ProfitLossType { get; set; }
    	[DataMember]
    	public Nullable<int> SpecialAccountType { get; set; }
    	[DataMember]
    	public Nullable<int> IsBankRelatedFlag { get; set; }
    	[DataMember]
    	public Nullable<int> RevalueStatusFlag { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual ICollection<ERP_AgentBrokerSalesMan> ERP_AgentBrokerSalesMan { get; set; }
    	[DataMember]
        public virtual FIN_AccountSubTypeCategory FIN_AccountSubTypeCategory { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_BankAccount> FIN_BankAccount { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_CostCenterwiseConfiguration> FIN_CostCenterwiseConfiguration { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_CostCenterwiseConfiguration> FIN_CostCenterwiseConfiguration1 { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_CostCenterwiseConfiguration> FIN_CostCenterwiseConfiguration2 { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_CostCenterwiseConfiguration> FIN_CostCenterwiseConfiguration3 { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_CostCenterwiseConfiguration> FIN_CostCenterwiseConfiguration4 { get; set; }
    	[DataMember]
        public virtual FIN_ProfitLostType FIN_ProfitLostType { get; set; }
    	[DataMember]
        public virtual FIN_SpecialAccountType FIN_SpecialAccountType { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_FixedTxnAttributes> ERP_FixedTxnAttributes { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_FixedTxnAttributes> ERP_FixedTxnAttributes1 { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_FixedTxnAttributes> ERP_FixedTxnAttributes2 { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_FixedTxnAttributes> ERP_FixedTxnAttributes3 { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_FixedTxnAttributes> ERP_FixedTxnAttributes4 { get; set; }
    	[DataMember]
        public virtual ICollection<FIN_ControledTransaction> FIN_ControledTransaction { get; set; }
    public FIN_GeneralLedgerAccount Clone(){
    	return this.MemberwiseClone() as FIN_GeneralLedgerAccount;
    }
    public override String ToString(){
       return AccountNo+"-"+ AccountNo;
    }
    }
}
