//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class HR_EMP_WARNINGS
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public int WRN_ID { get; set; }
    	[DataMember]
    	public string WRN_TYPE { get; set; }
    	[DataMember]
    	public string WRN_DESC { get; set; }
    	[DataMember]        
    	public Nullable<System.DateTime> WRN_DATE { get; set; }
    	[DataMember]
    	public string WRN_CREATED_BY { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    public HR_EMP_WARNINGS Clone(){
    	return this.MemberwiseClone() as HR_EMP_WARNINGS;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
