//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class HR_EMP_PASSPORT
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public decimal EP_SEQNO { get; set; }
    	[DataMember]
    	public string EP_PASSPORTNUMBER { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EP_PASSPORTISSUEDDATE { get; set; }
    	[DataMember]
    	public string EP_PLACEPASSPORTISSUED { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EP_PASSPORTEXPIREDATE { get; set; }
    	[DataMember]
    	public string EP_COMMENTS { get; set; }
    	[DataMember]
    	public string COU_CODE { get; set; }
    	[DataMember]
    	public Nullable<short> EP_NO_OF_ENTRIES { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    public HR_EMP_PASSPORT Clone(){
    	return this.MemberwiseClone() as HR_EMP_PASSPORT;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
