//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class HR_EMP_TRANSPORT
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public string ETPORT_MODE { get; set; }
    	[DataMember]
    	public string ETPORT_NEAR_STATION { get; set; }
    	[DataMember]
        [Values("Land","Sea","Air")]
    	public Nullable<short> ETPORT_COMMUTING_MODE { get; set; }
    	[DataMember]
    	public string ETPORT_COD_EMP_NUMBER { get; set; }
    	[DataMember]
    	public Nullable<double> ETPORT_DISTANCE { get; set; }
    	[DataMember]
    	public Nullable<double> ETPORT_DURATION { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    public HR_EMP_TRANSPORT Clone(){
    	return this.MemberwiseClone() as HR_EMP_TRANSPORT;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
