//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class HR_EMPLOYEE_TD
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public string EMP_PAYE_TAX_EXEMPT { get; set; }
    	[DataMember]
    	public Nullable<short> EMP_TAXONTAX_FLG { get; set; }
    	[DataMember]
    	public string EMP_TAX_ID_NUMBER { get; set; }
    	[DataMember]
    	public Nullable<short> EMP_EPF_ELIGIBLE_FLG { get; set; }
    	[DataMember]
    	public string EMP_EPF_NUMBER { get; set; }
    	[DataMember]
    	public Nullable<short> EMP_EPF_PAYMENT_TYPE_FLG { get; set; }
    	[DataMember]
    	public Nullable<decimal> EMP_EPF_EMPLOYEE_AMOUNT { get; set; }
    	[DataMember]
    	public Nullable<decimal> EMP_EPF_EMPLOYER_AMOUNT { get; set; }
    	[DataMember]
    	public Nullable<short> EMP_ETF_ELIGIBLE_FLG { get; set; }
    	[DataMember]
    	public string EMP_ETF_NUMBER { get; set; }
    	[DataMember]
    	public Nullable<decimal> EMP_ETF_EMPLOYEE_AMOUNT { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EMP_ETF_DATE { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    }
}
