//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class HR_EMP_MEMBER_DETAIL
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public string MEMBSHIP_CODE { get; set; }
    	[DataMember]
    	public string MEMBTYPE_CODE { get; set; }
    	[DataMember]
    	public string EMEMB_SUBSCRIPT_OWNERSHIP { get; set; }
    	[DataMember]
    	public Nullable<decimal> EMEMB_SUBSCRIPT_AMOUNT { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EMEMB_COMMENCE_DATE { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EMEMB_RENEWAL_DATE { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    	[DataMember]
        public virtual HR_MEMBERSHIP HR_MEMBERSHIP { get; set; }
    	[DataMember]
        public virtual HR_MEMBERSHIP_TYPE HR_MEMBERSHIP_TYPE { get; set; }
    public HR_EMP_MEMBER_DETAIL Clone(){
    	return this.MemberwiseClone() as HR_EMP_MEMBER_DETAIL;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
