//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class HR_EMPLOYEE_JS
    {
        public HR_EMPLOYEE_JS Clone()
        {
            return this.MemberwiseClone() as HR_EMPLOYEE_JS;
        }
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public string EMP_TYPE { get; set; }
    	[DataMember]
    	public string STAFFCAT_CODE { get; set; }
    	[DataMember]
    	public string CAT_CODE { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EMP_CONTARCT_START_DATE { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EMP_CONTRACT_END_DATE { get; set; }
    	[DataMember]
    	public Nullable<short> EMP_CONT_TO_PERM_FLG { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EMP_CONT_TO_PERM_DATE { get; set; }
    	[DataMember]
    	public Nullable<short> EMP_ACTIVE_HRM_FLG { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    	[DataMember]
        public virtual HR_JD_CATEGORY HR_JD_CATEGORY { get; set; }
    	[DataMember]
        public virtual HR_JD_CATEGORY HR_JD_CATEGORY1 { get; set; }
    }
}
