//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class HR_EMP_TRAININGS
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public int TN_ID { get; set; }
    	[DataMember]
    	public string TN_DESC { get; set; }
    	[DataMember]
    	public string TN_TYPE { get; set; }
    	[DataMember]
        [Values("Completed","Not Completed")]
    	public Nullable<short> TN_STATUS { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    public HR_EMP_TRAININGS Clone(){
    	return this.MemberwiseClone() as HR_EMP_TRAININGS;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
