//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class HR_EMP_RELATIONINFO
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public decimal EREL_DEPENDNO { get; set; }
    	[DataMember]
    	public string EREL_RELATIONSHIP { get; set; }
    	[DataMember]
    	public string EREL_RELATIONFULLNAME { get; set; }
    	[DataMember]
    	public Nullable<System.DateTime> EREL_BIRTHDAY { get; set; }
    	[DataMember]
    	public string EREL_NIC_NUMBER { get; set; }
    	[DataMember]
    	public Nullable<short> EREL_SEX_FLG { get; set; }
    	[DataMember]
    	public string EREL_TELEPHONE { get; set; }
    	[DataMember]
    	public string EREL_EDU_CENTRE { get; set; }
    	[DataMember]
    	public string EREL_OFFICE_ADDRESS { get; set; }
    	[DataMember]
    	public string EREL_HOUSE_ADDRESS { get; set; }
    	[DataMember]
    	public string EREL_SPOUSE_TELEPHONE { get; set; }
    	[DataMember]
    	public Nullable<short> EREL_WORK_SAME_COMP_FLG { get; set; }
    	[DataMember]
    	public string EREL_EMP_NUMBER { get; set; }
    	[DataMember]
    	public Nullable<short> EREL_ENTDEATHDONATION_FLG { get; set; }
    	[DataMember]
    	public Nullable<short> EREL_ENTMEDICALBENIFIT_FLG { get; set; }
    	[DataMember]
    	public Nullable<short> EREL_LIVINGORNOT_FLG { get; set; }
    	[DataMember]
    	public Nullable<short> EREL_PF_NOMINEE_FLG { get; set; }
    	[DataMember]
    	public Nullable<decimal> EREL_PF_RATIO { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE1 { get; set; }
    public HR_EMP_RELATIONINFO Clone(){
    	return this.MemberwiseClone() as HR_EMP_RELATIONINFO;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
