//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class HR_EMPLOYEE_PC
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public string EMP_PER_ADDRESS1 { get; set; }
    	[DataMember]
    	public string EMP_PER_ADDRESS2 { get; set; }
    	[DataMember]
    	public string EMP_PER_ADDRESS3 { get; set; }
    	[DataMember]
    	public string EMP_PER_CITY { get; set; }
    	[DataMember]
    	public string EMP_PER_POSTALCODE { get; set; }
    	[DataMember]
    	public string EMP_PER_TELEPHONE { get; set; }
    	[DataMember]
    	public string EMP_PER_MOBILE { get; set; }
    	[DataMember]
    	public string EMP_PER_FAX { get; set; }
    	[DataMember]
    	public string EMP_PER_EMAIL { get; set; }
    	[DataMember]
    	public string EMP_PER_COU_CODE { get; set; }
    	[DataMember]
    	public string EMP_PER_PROVINCE_CODE { get; set; }
    	[DataMember]
    	public string EMP_PER_DISTRICT_CODE { get; set; }
    	[DataMember]
    	public string EMP_PER_ELECTORATE_CODE { get; set; }
    
    	[DataMember]
        public virtual HR_COUNTRY HR_COUNTRY { get; set; }
    	[DataMember]
        public virtual HR_DISTRICT HR_DISTRICT { get; set; }
    	[DataMember]
        public virtual HR_ELECTORATE HR_ELECTORATE { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    	[DataMember]
        public virtual HR_PROVINCE HR_PROVINCE { get; set; }
    }
}
