//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class HR_JD_CATEGORY
    {
    	
        public HR_JD_CATEGORY()
        {
            this.HR_EMPLOYEE_JS = new HashSet<HR_EMPLOYEE_JS>();
            this.HR_EMPLOYEE_JS1 = new HashSet<HR_EMPLOYEE_JS>();
        }
        public override string ToString()
        {
            return JDCAT_CODE;
        } 
    	[DataMember]
    	public string JDCAT_CODE { get; set; }
    	[DataMember]
    	public string JDCAT_NAME { get; set; }
    	[DataMember]
    	public Nullable<short> STATUS_FLAG { get; set; }
    
    	[DataMember]
        public virtual ICollection<HR_EMPLOYEE_JS> HR_EMPLOYEE_JS { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMPLOYEE_JS> HR_EMPLOYEE_JS1 { get; set; }
    }
}
