//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_NONCASH_BENEFIT
    {
        string benefitCode;
        string name;
        public HR_NONCASH_BENEFIT()
        {
            this.HR_EMP_NONCASH_BENEFIT = new HashSet<HR_EMP_NONCASH_BENEFIT>();
        }
    
    	[DataMember]
        public string NBEN_CODE
        {
            get { return benefitCode; }
            set
            {
                if (value == "")
                {
                    throw new ValidationException("Benefit Code is empty! Please Fill!");
                }
                else
                {
                    benefitCode = value;
                }
            }
        }
    	[DataMember]
        public string NBEN_NAME
        {
            get { return name; }
            set
            {
                if (value == "")
                {
                    throw new ValidationException("Benefit Name is empty! Please Fill!");
                }
                else
                {
                    name = value;
                }
            }
        }
    	[DataMember]
        [Values("No", "Yes")]
    	public Nullable<short> NBEN_ITEM_RETURNABLE_FLG { get; set; }
    	[DataMember]
        [Values("Inactive", "Active")]
    	public Nullable<short> STATUS_FLAG { get; set; }
    
    	[DataMember]
        public virtual ICollection<HR_EMP_NONCASH_BENEFIT> HR_EMP_NONCASH_BENEFIT { get; set; }
    public HR_NONCASH_BENEFIT Clone(){
    	return this.MemberwiseClone() as HR_NONCASH_BENEFIT;
    }
    public override String ToString(){
       return NBEN_CODE.ToString();
    }
    }
}
