//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class HR_RELIGION
    {
    	
        public HR_RELIGION()
        {
            this.HR_EMPLOYEE_PD = new HashSet<HR_EMPLOYEE_PD>();
        }
        public override string ToString()
        {
            return RLG_CODE;
        }
    	[DataMember]
    	public string RLG_CODE { get; set; }
    	[DataMember]
    	public string RLG_NAME { get; set; }
    
    	[DataMember]
        public virtual ICollection<HR_EMPLOYEE_PD> HR_EMPLOYEE_PD { get; set; }
    }
}
