//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class HR_SALARY_GRADE
    {
    	
        public HR_SALARY_GRADE()
        {
            this.HR_CORPORATE_TITLE = new HashSet<HR_CORPORATE_TITLE>();
            this.HR_EMPLOYEE_JI = new HashSet<HR_EMPLOYEE_JI>();
        }
        public override string ToString()
        {
            return SAL_GRD_CODE;
        }    
    	[DataMember]
    	public string SAL_GRD_CODE { get; set; }
    	[DataMember]
    	public string SAL_GRD_NAME { get; set; }
    	[DataMember]
    	public string CURRENCY_ID { get; set; }
    	[DataMember]
    	public Nullable<short> STATUS_FLAG { get; set; }
    
    	[DataMember]
        public virtual ICollection<HR_CORPORATE_TITLE> HR_CORPORATE_TITLE { get; set; }
    	[DataMember]
        public virtual HR_CURRENCY HR_CURRENCY { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMPLOYEE_JI> HR_EMPLOYEE_JI { get; set; }
    }
}
