//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class ERP_UnitDefinition
    {
    	
        public ERP_UnitDefinition()
        {
            this.ERP_UnitConversion = new HashSet<ERP_UnitConversion>();
            this.ERP_UnitConversion1 = new HashSet<ERP_UnitConversion>();
            this.ERP_UnitDefinition1 = new HashSet<ERP_UnitDefinition>();
        }
    
    	[DataMember]
    	public string UnitCode { get; set; }
    	[DataMember]
    	public string StandardSyntax { get; set; }
    	[DataMember]
    	public string UnitDescription { get; set; }
    	[DataMember]
    	public string MajorUnitCode { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual ICollection<ERP_UnitConversion> ERP_UnitConversion { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_UnitConversion> ERP_UnitConversion1 { get; set; }
    	[DataMember]
        public virtual ICollection<ERP_UnitDefinition> ERP_UnitDefinition1 { get; set; }
    	[DataMember]
        public virtual ERP_UnitDefinition ERP_UnitDefinition2 { get; set; }
    public ERP_UnitDefinition Clone(){
    	return this.MemberwiseClone() as ERP_UnitDefinition;
    }
    public override String ToString(){
       return UnitCode.ToString();
    }
    }
}
