//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class ERP_UnitConversion
    {
    	[DataMember]
    	public string FromUnitCode { get; set; }
    	[DataMember]
    	public string ToUnitCode { get; set; }
    	[DataMember]
    	public Nullable<decimal> ConversionFactor { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual ERP_UnitDefinition ERP_UnitDefinition { get; set; }
    	[DataMember]
        public virtual ERP_UnitDefinition ERP_UnitDefinition1 { get; set; }
    public ERP_UnitConversion Clone(){
    	return this.MemberwiseClone() as ERP_UnitConversion;
    }
    public override String ToString(){
       return FromUnitCode.ToString();
    }
    }
}
