//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class ERP_FixedTxnAttributes
    {
    	[DataMember]
    	public string DocCode { get; set; }
    	[DataMember]
    	public string TxCode { get; set; }
    	[DataMember]
    	public string GLCode { get; set; }
    	[DataMember]
    	public string Cost_Dbt_GLAccCode { get; set; }
    	[DataMember]
    	public string Cost_Dbt_CostCenterCode { get; set; }
    	[DataMember]
    	public string Cost_Dbt_CurrencyCode { get; set; }
    	[DataMember]
    	public string Cost_Crd_GLAccCode { get; set; }
    	[DataMember]
    	public string Cost_Crd_CostCenterCode { get; set; }
    	[DataMember]
    	public string Cost_Crd_CurrencyCode { get; set; }
    	[DataMember]
    	public string Sales_Dbt_GLAccCode { get; set; }
    	[DataMember]
    	public string Sales_Dbt_CostCenterCode { get; set; }
    	[DataMember]
    	public string Sales_Dbt_CurrencyCode { get; set; }
    	[DataMember]
    	public string Sales_Crd_GLAccCode { get; set; }
    	[DataMember]
    	public string Sales_Crd_CostCenterCode { get; set; }
    	[DataMember]
    	public string Sales_Crd_CurrencyCode { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }

        private ERP_DocumentAttributes _ERP_DocumentAttributes;
        [DataMember]
        public virtual ERP_DocumentAttributes ERP_DocumentAttributes
        {
            get
            {
                return _ERP_DocumentAttributes;
            }
            set
            {
                if (value == null)
                    throw new ValidationException("Document Attributes is required");

                _ERP_DocumentAttributes = value;
            }
        }
        private FIN_GeneralLedgerAccount _FIN_GeneralLedgerAccount;
        [DataMember]
        public virtual FIN_GeneralLedgerAccount FIN_GeneralLedgerAccount
        {
            get
            {
                return _FIN_GeneralLedgerAccount;
            }
            set
            {
                if (value == null)
                    throw new ValidationException("General Ledger Account is required");

                _FIN_GeneralLedgerAccount = value;
            }
        }
    	[DataMember]
        public virtual FIN_GeneralLedgerAccount FIN_GeneralLedgerAccount1 { get; set; }
    	[DataMember]
        public virtual FIN_CostCenter FIN_CostCenter { get; set; }
    	[DataMember]
        public virtual FIN_Currency FIN_Currency { get; set; }
    	[DataMember]
        public virtual FIN_CostCenter FIN_CostCenter1 { get; set; }
    	[DataMember]
        public virtual FIN_Currency FIN_Currency1 { get; set; }
    	[DataMember]
        public virtual FIN_GeneralLedgerAccount FIN_GeneralLedgerAccount2 { get; set; }
    	[DataMember]
        public virtual FIN_CostCenter FIN_CostCenter2 { get; set; }
    	[DataMember]
        public virtual FIN_Currency FIN_Currency2 { get; set; }
    	[DataMember]
        public virtual FIN_GeneralLedgerAccount FIN_GeneralLedgerAccount3 { get; set; }
    	[DataMember]
        public virtual FIN_CostCenter FIN_CostCenter3 { get; set; }
    	[DataMember]
        public virtual FIN_Currency FIN_Currency3 { get; set; }
    	[DataMember]
        public virtual FIN_GeneralLedgerAccount FIN_GeneralLedgerAccount4 { get; set; }
    public ERP_FixedTxnAttributes Clone(){
    	return this.MemberwiseClone() as ERP_FixedTxnAttributes;
    }
    public override String ToString(){
       return DocCode.ToString();
    }
    }
}
