//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class FIN_TxnReference
    {
    	[DataMember]
    	public string DocCode { get; set; }
    	[DataMember]
    	public string TxCode { get; set; }
    	[DataMember]
    	public short RefSeq { get; set; }
    	[DataMember]
    	public Nullable<int> SeqNo { get; set; }
    	[DataMember]
    	public string ReferenceText { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
        private ERP_DocumentAttributes _ERP_DocumentAttributes;
    	[DataMember]
        public virtual ERP_DocumentAttributes ERP_DocumentAttributes
        {
            get
            {
                return _ERP_DocumentAttributes;
            }
            set
            {
                if (value == null)
                    throw new ValidationException("Document Attributes is required");

                _ERP_DocumentAttributes = value;
            }
        }
    public FIN_TxnReference Clone(){
    	return this.MemberwiseClone() as FIN_TxnReference;
    }
    public override String ToString(){
       return DocCode.ToString();
    }
    }
}
