//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Text.RegularExpressions;
    using System.ComponentModel.DataAnnotations;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference=true)]
    public partial class FIN_CurrencyExchangeRate
    {
        private Int16 backing_CalenderYear;
        private byte backing_CalenderMonth;       

    	[DataMember]
    	public string CurrencyCode { get; set; }
    	[DataMember]
    	public short CalenderYear 
        {
            get
            {
                return backing_CalenderYear;
            }
            set
            {
                string check_value = value.ToString();
                if (Regex.IsMatch(check_value, @"^[0-9]{4}$"))
                {
                    backing_CalenderYear = value;
                }
                else
                { 
                    throw new ValidationException("Calender year must be an number of four digits");
                }
            }
        }
    	[DataMember]
        public byte CalenderMonth 
        {
            get
            {
                return backing_CalenderMonth;
            }
            set
            {                
                if (0<value && value<13)
                {
                    backing_CalenderMonth = value;
                }
                else
                {
                    throw new ValidationException("Calender month is invalid");
                }
            }
        }
    	[DataMember]
    	public Nullable<decimal> StandardRate { get; set; }
    	[DataMember]
    	public Nullable<decimal> BuyRate { get; set; }
    	[DataMember]
    	public Nullable<decimal> MiddleRate { get; set; }
    	public string EnteredFrom { get; set; }
    	public string EnteredUser { get; set; }
    	public Nullable<System.DateTime> EnteredDate { get; set; }
    	public string ModifiedFrom { get; set; }
    	public string ModifiedUser { get; set; }
    	public Nullable<System.DateTime> ModifiedDate { get; set; }
    
    	[DataMember]
        public virtual FIN_Currency FIN_Currency { get; set; }
    public FIN_CurrencyExchangeRate Clone(){
    	return this.MemberwiseClone() as FIN_CurrencyExchangeRate;
    }
    public override String ToString(){
       return CurrencyCode.ToString();
    }
    }
}
