//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_BRANCH
    {
    	
        public HR_BRANCH()
        {
            this.HR_EMP_BANK = new HashSet<HR_EMP_BANK>();
        }
    
    	[DataMember]
    	public string BBRANCH_CODE { get; set; }
    	[DataMember]
    	public string BANK_CODE { get; set; }
    	[DataMember]
    	public string BBRANCH_NAME { get; set; }
    	[DataMember]
    	public string BBRANCH_ADDRESS { get; set; }
    	[DataMember]
    	public Nullable<short> STATUS_FLAG { get; set; }
    
    	[DataMember]
        public virtual HR_BANK HR_BANK { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_BANK> HR_EMP_BANK { get; set; }
    public HR_BRANCH Clone(){
    	return this.MemberwiseClone() as HR_BRANCH;
    }
    public override String ToString(){
       return BBRANCH_CODE.ToString();
    }
    }
}
