//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_CURRENCY
    {
    	
        public HR_CURRENCY()
        {
            this.HR_SALARY_GRADE = new HashSet<HR_SALARY_GRADE>();
            this.HR_EMP_BASICSALARY = new HashSet<HR_EMP_BASICSALARY>();
        }
    
    	[DataMember]
    	public string CURRENCY_ID { get; set; }
    	[DataMember]
    	public string CURRENCY_NAME { get; set; }
    	[DataMember]
    	public Nullable<short> STATUS_FLAG { get; set; }
    
    	[DataMember]
        public virtual ICollection<HR_SALARY_GRADE> HR_SALARY_GRADE { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_BASICSALARY> HR_EMP_BASICSALARY { get; set; }
    public HR_CURRENCY Clone(){
    	return this.MemberwiseClone() as HR_CURRENCY;
    }
    public override String ToString(){
       return CURRENCY_ID.ToString();
    }
    }
}
