//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_EMP_EXTRA_ACTIVITY
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public int EEXTACT_SEQNO { get; set; }
    	[DataMember]
    	public string EACAT_CODE { get; set; }
    	[DataMember]
    	public string EATYPE_CODE { get; set; }
    	[DataMember]
    	public string EEXTACT_ACHIEVEMENT { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    public HR_EMP_EXTRA_ACTIVITY Clone(){
    	return this.MemberwiseClone() as HR_EMP_EXTRA_ACTIVITY;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
