//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_EMP_BASICSALARY
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public int SAL_DTL_YEAR { get; set; }
    	[DataMember]
    	public string SAL_GRD_CODE { get; set; }
    	[DataMember]
    	public string CURRENCY_ID { get; set; }
    	[DataMember]
    	public Nullable<double> EBSAL_BASIC_SALARY { get; set; }
    
    	[DataMember]
        public virtual HR_CURRENCY HR_CURRENCY { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    	[DataMember]
        public virtual HR_SALARY_GRADE HR_SALARY_GRADE { get; set; }
    public HR_EMP_BASICSALARY Clone(){
    	return this.MemberwiseClone() as HR_EMP_BASICSALARY;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
