//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class HR_EMPLOYEE_CDWD
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public string EMP_TEM_ADDRESS1 { get; set; }
    	[DataMember]
    	public string EMP_TEM_ADDRESS2 { get; set; }
    	[DataMember]
    	public string EMP_TEM_ADDRESS3 { get; set; }
    	[DataMember]
    	public string EMP_TEM_CITY { get; set; }
    	[DataMember]
    	public string EMP_TEM_POSTALCODE { get; set; }
    	[DataMember]
    	public string EMP_TEM_TELEPHONE { get; set; }
    	[DataMember]
    	public string EMP_TEM_MOBILE { get; set; }
    	[DataMember]
    	public string EMP_TEM_FAX { get; set; }
    	[DataMember]
    	public string EMP_TEM_EMAIL { get; set; }
    	[DataMember]
    	public string EMP_TEM_COU_CODE { get; set; }
    	[DataMember]
    	public string EMP_TEM_PROVINCE_CODE { get; set; }
    	[DataMember]
    	public string EMP_TEM_DISTRICT_CODE { get; set; }
    	[DataMember]
    	public string EMP_TEM_ELECTORATE_CODE { get; set; }
    
    	[DataMember]
        public virtual HR_COUNTRY HR_COUNTRY { get; set; }
    	[DataMember]
        public virtual HR_DISTRICT HR_DISTRICT { get; set; }
    	[DataMember]
        public virtual HR_ELECTORATE HR_ELECTORATE { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    	[DataMember]
        public virtual HR_PROVINCE HR_PROVINCE { get; set; }

        public HR_EMPLOYEE_CDWD Clone()
        {
            return this.MemberwiseClone() as HR_EMPLOYEE_CDWD;
        }
    }
}
