//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_EMPLOYEE
    {
    	
        public HR_EMPLOYEE()
        {
            this.HR_EMP_ATTACHMENT = new HashSet<HR_EMP_ATTACHMENT>();
            this.HR_EMP_PASSPORT = new HashSet<HR_EMP_PASSPORT>();
            this.HR_EMP_RELATIONINFO = new HashSet<HR_EMP_RELATIONINFO>();
            this.HR_EMP_RELATIONINFO1 = new HashSet<HR_EMP_RELATIONINFO>();
            this.HR_EMP_TRAININGS = new HashSet<HR_EMP_TRAININGS>();
            this.HR_EMP_WARNINGS = new HashSet<HR_EMP_WARNINGS>();
            this.HR_EMP_MEMBER_DETAIL = new HashSet<HR_EMP_MEMBER_DETAIL>();
            this.HR_EMP_QUALIFICATION = new HashSet<HR_EMP_QUALIFICATION>();
            this.HR_EMP_CASH_BENEFIT = new HashSet<HR_EMP_CASH_BENEFIT>();
            this.HR_EMP_NONCASH_BENEFIT = new HashSet<HR_EMP_NONCASH_BENEFIT>();
            this.HR_EMP_BASICSALARY = new HashSet<HR_EMP_BASICSALARY>();
            this.HR_EMP_EXTRA_ACTIVITY = new HashSet<HR_EMP_EXTRA_ACTIVITY>();
            this.HR_EMP_JOBSPEC = new HashSet<HR_EMP_JOBSPEC>();
            this.HR_EMP_LANGUAGE = new HashSet<HR_EMP_LANGUAGE>();
            this.HR_EMP_REPORTTO = new HashSet<HR_EMP_REPORTTO>();
            this.HR_EMP_REPORTTO1 = new HashSet<HR_EMP_REPORTTO>();
            this.HR_EMP_BANK = new HashSet<HR_EMP_BANK>();
        }
    
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public string EMP_TITLE { get; set; }
    	[DataMember]
    	public string EMP_CALLING_NAME { get; set; }
    	[DataMember]
    	public string EMP_SURNAME { get; set; }
    	[DataMember]
    	public string EMP_MAIDEN_NAME { get; set; }
    	[DataMember]
    	public string EMP_MIDDLE_INI { get; set; }
    	[DataMember]
    	public string EMP_NAMES_BY_INI { get; set; }
    	[DataMember]
    	public string EMP_FULLNAME { get; set; }
    	[DataMember]
    	public string EMP_OTHER_NAMES { get; set; }
    
    	[DataMember]
        public virtual ICollection<HR_EMP_ATTACHMENT> HR_EMP_ATTACHMENT { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_PASSPORT> HR_EMP_PASSPORT { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_RELATIONINFO> HR_EMP_RELATIONINFO { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_RELATIONINFO> HR_EMP_RELATIONINFO1 { get; set; }
    	[DataMember]
        public virtual HR_EMP_EMERGENCY HR_EMP_EMERGENCY { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_TRAININGS> HR_EMP_TRAININGS { get; set; }
    	[DataMember]
        public virtual HR_EMP_TRANSPORT HR_EMP_TRANSPORT { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_WARNINGS> HR_EMP_WARNINGS { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_MEMBER_DETAIL> HR_EMP_MEMBER_DETAIL { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_QUALIFICATION> HR_EMP_QUALIFICATION { get; set; }
    	[DataMember]
        public virtual HR_EMP_WORK_EXPERIENCE HR_EMP_WORK_EXPERIENCE { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE_PD HR_EMPLOYEE_PD { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE_JI HR_EMPLOYEE_JI { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE_JS HR_EMPLOYEE_JS { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE_TD HR_EMPLOYEE_TD { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE_PC HR_EMPLOYEE_PC { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE_CDWD HR_EMPLOYEE_CDWD { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE_OC HR_EMPLOYEE_OC { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE_EIM_WS HR_EMPLOYEE_EIM_WS { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_CASH_BENEFIT> HR_EMP_CASH_BENEFIT { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_NONCASH_BENEFIT> HR_EMP_NONCASH_BENEFIT { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_BASICSALARY> HR_EMP_BASICSALARY { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_EXTRA_ACTIVITY> HR_EMP_EXTRA_ACTIVITY { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_JOBSPEC> HR_EMP_JOBSPEC { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_LANGUAGE> HR_EMP_LANGUAGE { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_REPORTTO> HR_EMP_REPORTTO { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_REPORTTO> HR_EMP_REPORTTO1 { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_BANK> HR_EMP_BANK { get; set; }
    public HR_EMPLOYEE Clone(){
    	return this.MemberwiseClone() as HR_EMPLOYEE;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
