//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    [DataContract(IsReference = true)]
    public partial class HR_EMPLOYEE_OC
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public string EMP_OFFICE_PHONE { get; set; }
    	[DataMember]
    	public string EMP_OFFICE_EXTN { get; set; }
    	[DataMember]
    	public string EMP_OFFICE_EMAIL { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }

        public HR_EMPLOYEE_OC Clone()
        {
            return this.MemberwiseClone() as HR_EMPLOYEE_OC;
        }
    }
}
