//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_EMP_BANK
    {
    	[DataMember]
    	public string EMP_NUMBER { get; set; }
    	[DataMember]
    	public string BBRANCH_CODE { get; set; }
    	[DataMember]
    	public string BANK_CODE { get; set; }
    	[DataMember]
    	public string EBANK_ACC_NO { get; set; }
    	[DataMember]
    	public Nullable<short> EBANK_ACC_TYPE_FLG { get; set; }
    	[DataMember]
    	public Nullable<decimal> EBANK_AMOUNT { get; set; }
    	[DataMember]
    	public Nullable<decimal> EBANK_ORDER { get; set; }
    
    	[DataMember]
        public virtual HR_BANK HR_BANK { get; set; }
    	[DataMember]
        public virtual HR_BRANCH HR_BRANCH { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    public HR_EMP_BANK Clone(){
    	return this.MemberwiseClone() as HR_EMP_BANK;
    }
    public override String ToString(){
       return EMP_NUMBER.ToString();
    }
    }
}
