//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_EMP_REPORTTO
    {
    	[DataMember]
    	public string EREP_SUP_EMP_NUMBER { get; set; }
    	[DataMember]
    	public string EREP_SUB_EMP_NUMBER { get; set; }
    	[DataMember]
        [Values("Direct", "Indirect","Subordinates")]
    	public short EREP_REPORTING_MODE { get; set; }
    	[DataMember]
    	public Nullable<int> EREP_REPORTING_SEQUENCE { get; set; }
    
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE { get; set; }
    	[DataMember]
        public virtual HR_EMPLOYEE HR_EMPLOYEE1 { get; set; }
    public HR_EMP_REPORTTO Clone(){
    	return this.MemberwiseClone() as HR_EMP_REPORTTO;
    }
    public override String ToString(){
       return EREP_SUP_EMP_NUMBER.ToString();
    }
    }
}
