//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_LANGUAGE
    {
    	
        public HR_LANGUAGE()
        {
            this.HR_EMP_LANGUAGE = new HashSet<HR_EMP_LANGUAGE>();
        }
    
    	[DataMember]
    	public string LANG_CODE { get; set; }
    	[DataMember]
    	public string LANG_Name { get; set; }
    
    	[DataMember]
        public virtual ICollection<HR_EMP_LANGUAGE> HR_EMP_LANGUAGE { get; set; }
    public HR_LANGUAGE Clone(){
    	return this.MemberwiseClone() as HR_LANGUAGE;
    }
    public override String ToString(){
       return LANG_CODE.ToString();
    }
    }
}
