//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBiz.MDMAPI.Common.Entities
{
    using System;
    using System.Collections.Generic;
    
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
       
    [DataContract(IsReference=true)]
    public partial class HR_SALARY_GRADE
    {
    	
        public HR_SALARY_GRADE()
        {
            this.HR_CORPORATE_TITLE = new HashSet<HR_CORPORATE_TITLE>();
            this.HR_EMPLOYEE_JI = new HashSet<HR_EMPLOYEE_JI>();
            this.HR_EMP_BASICSALARY = new HashSet<HR_EMP_BASICSALARY>();
        }
    
    	[DataMember]
    	public string SAL_GRD_CODE { get; set; }
    	[DataMember]
    	public string SAL_GRD_NAME { get; set; }
    	[DataMember]
    	public string CURRENCY_ID { get; set; }
    	[DataMember]
    	public Nullable<short> STATUS_FLAG { get; set; }
    
    	[DataMember]
        public virtual ICollection<HR_CORPORATE_TITLE> HR_CORPORATE_TITLE { get; set; }
    	[DataMember]
        public virtual HR_CURRENCY HR_CURRENCY { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMPLOYEE_JI> HR_EMPLOYEE_JI { get; set; }
    	[DataMember]
        public virtual ICollection<HR_EMP_BASICSALARY> HR_EMP_BASICSALARY { get; set; }
    public HR_SALARY_GRADE Clone(){
    	return this.MemberwiseClone() as HR_SALARY_GRADE;
    }
    public override String ToString(){
       return SAL_GRD_CODE.ToString();
    }
    }
}
